---
# Source: oes/templates/secrets/opsmx-gitops-secret.yaml
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  gitcloneparam: https://phanikuarp:encrypted%3Agittoken%3Agittoken@github.com/phanikumarp/313standred.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://github.com/phanikumarp/313standred.git
  gituser: phanikuarp
  gittoken: encrypted:gittoken:gittoken
  dynamicAccRepository: 313standred

kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
